### ISSUE TITLE
Not working on 1.17

### ISSUE THREAD

**Issue by ShaneBeee** [Shynixn/StructureBlockLib#83]
I am getting a giant error when I run my plugin on 1.17:
https://paste.md-5.net/oyaxapomux.cs

I think this may be due to:
https://github.com/Shynixn/StructureBlockLib/blob/bec80e76a275e6f875ce47af67bf661e4a259bcb/structureblocklib-bukkit-core/bukkit-nms-117R1/build.gradle.kts#L5

I could be wrong but it appears you are using the Mojang mappings (which are not intended for plugin distribution) therefor the error states its looking for a class that I'm assuming is Mojang mapped and not Bukkit mapped.

The line that made me think this:
```
Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/level/levelgen/structure/templatesystem/StructureProcessor
```
And that is not a class in a spigot jar:
<img width="513" alt="Screen Shot 2021-06-19 at 6 10 25 PM" src="https://user-images.githubusercontent.com/20008482/122659160-afe7cb00-d129-11eb-8ceb-08bd3e465444.png">

EDIT:
to add to this, I decompiled the jar you are distributing which appears to have the correct mappings, but the version that is grabbed from Maven (via my plugin) does not

**Comment by Shynixn** [comment]
I think something is wrong in the build script which does not apply the mappings for the structureblocklib-core jar. Thanks for reporting, I'll fix it.

**Comment by Shynixn** [comment]
I have decompiled the newly deployed ``structureblocklib-bukkit-core-2.2.2.jar`` and it seems to be correct now. I'll close the issue.

https://repo1.maven.org/maven2/com/github/shynixn/structureblocklib/structureblocklib-bukkit-core/2.2.2/
